export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS"
export const GET_ALL_APPOINTMENTS_SUCCESS = "GET_ALL_APPOINTMENTS_SUCCESS"
export const GET_ALL_APPOINTMENTS_FAIL = "GET_ALL_APPOINTMENTS_FAIL"