export const GET_ALL_STAFF_MEMBERS = "GET_ALL_STAFF_MEMBERS"
export const GET_ALL_STAFF_MEMBERS_SUCCESS = "GET_ALL_STAFF_MEMBERS_SUCCESS"
export const GET_ALL_STAFF_MEMBERS_FAIL = "GET_ALL_STAFF_MEMBERS_FAIL"